-- ===========================================================================
-- OIML R76 Digital Test Report System — schema
--
-- Two rules govern this schema:
--
--  1. No derived value is stored. Error, corrected error, n_i, MPE and pass/fail
--     are computed by @r76/domain on read. Observation rows hold only what the
--     technician actually entered (load and indications). This is spec
--     requirement 7, and it means a rule change re-judges historical data
--     instead of leaving stale verdicts behind.
--
--  2. Instrument facts live in exactly one place. test_run carries environment
--     conditions but never Max/e/n/class — those are read from instrument_model.
-- ===========================================================================

-- Journal mode is set in db/index.ts, not here: WAL is attempted first and falls back
-- to the rollback journal on filesystems that cannot host a WAL shared-memory file.
CREATE TABLE IF NOT EXISTS "user" (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT    NOT NULL,
  email          TEXT    NOT NULL UNIQUE,
  password_hash  TEXT    NOT NULL,
  role           TEXT    NOT NULL CHECK (role IN ('admin', 'technician')),
  -- Standing signature image for report signing, uploaded from the profile page.
  -- Stored as a file name under the uploads directory, same convention as attachments.
  signature_path TEXT,
  -- Admins deactivate accounts instead of deleting them, so history keeps its names.
  is_active      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS manufacturer (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name           TEXT    NOT NULL,
  address        TEXT,
  contact_person TEXT,
  email          TEXT,
  phone          TEXT,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- One type-examination campaign (the "Task" in DELTA's vocabulary).
CREATE TABLE IF NOT EXISTS project (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  manufacturer_id        INTEGER NOT NULL REFERENCES manufacturer(id) ON DELETE CASCADE,
  task_no                TEXT    NOT NULL,
  report_no              TEXT    NOT NULL,
  danak_no               TEXT,
  -- Drives which test_type and checklist_item rows apply. A future OIML revision
  -- is a new standard string plus new seed rows, not a code change.
  standard_version       TEXT    NOT NULL DEFAULT 'OIML R76-1:2006',
  examination_start_date TEXT,
  examination_end_date   TEXT,
  status                 TEXT    NOT NULL DEFAULT 'draft'
                                 CHECK (status IN ('draft','reviewed','approved')),
  created_by             INTEGER REFERENCES "user"(id),
  -- Legacy review columns remain for compatibility with existing databases.
  review_feedback        TEXT,
  reviewed_by            INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
  reviewed_at            TIMESTAMPTZ,
  approved_by            INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
  approved_at            TIMESTAMPTZ,
  created_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_project_manufacturer ON project(manufacturer_id);
CREATE INDEX IF NOT EXISTS idx_project_status       ON project(status);
CREATE INDEX IF NOT EXISTS idx_project_report_no    ON project(report_no);

CREATE TABLE IF NOT EXISTS instrument_family (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  family_name TEXT    NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_family_project ON instrument_family(project_id);

-- The single source of truth for every instrument fact. Every test screen reads
-- its read-only header from here.
CREATE TABLE IF NOT EXISTS instrument_model (
  id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family_id                   INTEGER NOT NULL REFERENCES instrument_family(id) ON DELETE CASCADE,
  model_name                  TEXT    NOT NULL,

  max_capacity                REAL    NOT NULL,
  min_capacity                REAL    NOT NULL,
  e_value                     REAL    NOT NULL CHECK (e_value > 0),
  d_value                     REAL    NOT NULL CHECK (d_value > 0),
  -- Stored because it is printed on the report and marked on the instrument, but
  -- always written as round(max/e) by the API rather than accepted from a form.
  n_intervals                 INTEGER NOT NULL,
  accuracy_class              TEXT    NOT NULL DEFAULT 'II'
                                      CHECK (accuracy_class IN ('I','II','III','IIII')),
  fractional_factor_pi        REAL    NOT NULL DEFAULT 1,

  load_cell_type              TEXT,
  load_cell_manufacturer      TEXT,
  load_cell_capacity          TEXT,
  load_cell_rated_output_mvv  REAL,
  load_cell_min_impedance_ohm REAL,

  -- JSON blobs: these are checklist-style booleans reported verbatim, never
  -- queried or joined on, so a column per flag would be noise.
  zero_setting_types          JSONB   NOT NULL DEFAULT '{}'::jsonb,
  tare_types                  JSONB   NOT NULL DEFAULT '{}'::jsonb,
  max_tare_pct                REAL,

  operating_temp_min          REAL,
  operating_temp_max          REAL,
  power_ac_nominal_v          REAL,
  power_ac_min_v              REAL,
  power_ac_max_v              REAL,
  power_dc_nominal_v          REAL,
  power_dc_min_v              REAL,
  power_dc_max_v              REAL,

  -- Absolute span-stability tolerance (mpd). Per model, deliberately not a global
  -- constant, because it is an instrument property rather than a rule of the standard.
  mpd_span_stability          REAL    NOT NULL DEFAULT 0.25,

  pan_shape                   TEXT    NOT NULL DEFAULT 'rectangular_4corner'
                                      CHECK (pan_shape IN ('rectangular_4corner','triangular_3point')),
  serial_no                   TEXT,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_model_family ON instrument_model(family_id);

CREATE TABLE IF NOT EXISTS reference_weight (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id           INTEGER NOT NULL REFERENCES instrument_model(id) ON DELETE CASCADE,
  nominal_load_value REAL    NOT NULL,
  sequence_order     INTEGER NOT NULL,
  UNIQUE (model_id, sequence_order)
);

CREATE INDEX IF NOT EXISTS idx_refweight_model ON reference_weight(model_id);

-- Master data. Seeded from @r76/domain's TEST_TYPES catalogue.
CREATE TABLE IF NOT EXISTS test_type (
  code                       TEXT PRIMARY KEY,
  display_name               TEXT NOT NULL,
  description                TEXT,
  applicable_standards       JSONB NOT NULL DEFAULT '[]'::jsonb,
  rule_type                  TEXT NOT NULL
                                  CHECK (rule_type IN ('MPE_TABLE','FIXED_VALUE','DERIVED_NO_ENTRY')),
  fixed_tolerance_expression TEXT,
  form_kind                  TEXT,
  report_sheet_ref           TEXT,
  category                   TEXT,
  implemented                BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order                 INTEGER NOT NULL DEFAULT 0
);

-- One performance of one test on one model.
CREATE TABLE IF NOT EXISTS test_run (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  model_id         INTEGER NOT NULL REFERENCES instrument_model(id) ON DELETE CASCADE,
  test_type_code   TEXT    NOT NULL REFERENCES test_type(code),
  status           TEXT    NOT NULL DEFAULT 'not_started'
                           CHECK (status IN ('not_started','in_progress','complete')),

  temperature_c    REAL,
  chamber_temp_c   REAL,
  room_temp_c      REAL,
  humidity_pct     REAL,
  -- Barometric pressure, hPa (OIML operating envelope 860–1060).
  barometric_hpa   REAL,
  date_performed   TEXT,
  time_performed   TEXT,
  operator_name    TEXT,

  -- Test-specific parameters that are inputs, not instrument facts.
  test_load        REAL,     -- REP, ECC, EMC_ESD: the load under test
  indication_zero  REAL,     -- REP: the I0 subtracted to give P
  remarks          TEXT,

  -- Cached rollup, refreshed on every write by the API. The authoritative verdict is
  -- always recomputed from observations; this column exists so the dashboard and
  -- report repository can sort and filter without loading every observation row.
  overall_pass     INTEGER,

  created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (model_id, test_type_code)
);

CREATE INDEX IF NOT EXISTS idx_testrun_model ON test_run(model_id);

-- Rows inside a test run's data table. Only entered values live here.
CREATE TABLE IF NOT EXISTS observation (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_run_id     INTEGER NOT NULL REFERENCES test_run(id) ON DELETE CASCADE,
  sequence_no     INTEGER NOT NULL,

  load_value      REAL    NOT NULL,
  indication_up   REAL,
  indication_down REAL,

  -- Changeover small weights ΔL per direction (R76 changeover method).
  -- Null means direct reading; the rules treat an absent ΔL as zero.
  delta_l_up      REAL,
  delta_l_down    REAL,

  -- Eccentricity
  position_code   TEXT,
  position_label  TEXT,
  load_zero       REAL,
  indication_zero REAL,

  -- ESD
  test_voltage_kv   REAL,
  application_mode  TEXT,
  polarity          TEXT,
  indication_before REAL,
  indication_after  REAL,

  -- Radiated immunity (frequency sweep at fixed field strength)
  frequency_mhz       REAL,
  field_strength_v_m  REAL,

  -- Span stability
  condition   TEXT,
  measured_at TEXT,

  UNIQUE (test_run_id, sequence_no)
);

CREATE INDEX IF NOT EXISTS idx_observation_run ON observation(test_run_id);

-- Master data, versioned by standard.
CREATE TABLE IF NOT EXISTS checklist_item (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clause_no            TEXT    NOT NULL,
  description          TEXT    NOT NULL,
  category             TEXT,
  applicable_standards JSONB   NOT NULL DEFAULT '[]'::jsonb,
  sort_order           INTEGER NOT NULL DEFAULT 0,
  UNIQUE (clause_no, description)
);

CREATE TABLE IF NOT EXISTS project_checklist_result (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id         INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  checklist_item_id  INTEGER NOT NULL REFERENCES checklist_item(id) ON DELETE CASCADE,
  applicable         TEXT    NOT NULL DEFAULT 'existent'
                             CHECK (applicable IN ('existent','non_existent','na')),
  status             TEXT    NOT NULL DEFAULT 'na'
                             CHECK (status IN ('pass','fail','na')),
  remarks            TEXT,
  -- Links a clause to the test run that evidences it.
  linked_test_run_id INTEGER REFERENCES test_run(id) ON DELETE SET NULL,
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (project_id, checklist_item_id)
);

CREATE INDEX IF NOT EXISTS idx_checklistresult_project ON project_checklist_result(project_id);

CREATE TABLE IF NOT EXISTS attachment (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  model_id    INTEGER REFERENCES instrument_model(id) ON DELETE CASCADE,
  test_run_id INTEGER REFERENCES test_run(id) ON DELETE CASCADE,
  file_path   TEXT    NOT NULL,
  original_name TEXT,
  mime_type   TEXT,
  caption     TEXT,
  uploaded_by TEXT,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_attachment_project ON attachment(project_id);
CREATE INDEX IF NOT EXISTS idx_attachment_run     ON attachment(test_run_id);

CREATE TABLE IF NOT EXISTS signature (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id           INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  signed_by_name       TEXT    NOT NULL,
  signed_by_title      TEXT,
  signed_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  signature_image_path TEXT,
  -- Who signed, as a user id. Names and signature images are read live from the
  -- user row at report time, so a rename or re-upload is reflected without re-signing.
  signed_by_user_id    INTEGER REFERENCES "user"(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_signature_project ON signature(project_id);

-- Report generation is re-triggerable; every run appends a row so the history is
-- auditable rather than overwritten.
CREATE TABLE IF NOT EXISTS generated_report (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id    INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  report_no     TEXT,
  format        TEXT    NOT NULL DEFAULT 'html'
    CONSTRAINT chk_generated_report_format CHECK (format IN ('html','pdf','docx','xlsx')),
  file_path     TEXT    NOT NULL,
  generated_by  TEXT,
  generated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- Verdict snapshot at generation time, so the repository can be searched by
  -- outcome without recomputing every historical report.
  overall_verdict TEXT,
  test_count      INTEGER,
  pass_count      INTEGER,
  fail_count      INTEGER,
  -- Whether the signature block printed on this generation. Part of the record
  -- because two generations of the same data may legitimately differ here.
  print_signature BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_report_project ON generated_report(project_id);
CREATE INDEX IF NOT EXISTS idx_report_date    ON generated_report(generated_at);

-- Manufacturer status link. One active row per project (revoked rows stay for audit).
-- The token is an unguessable opaque string; the public API looks up by token only,
-- never by sequential project id, so projects cannot be enumerated.
CREATE TABLE IF NOT EXISTS project_share (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id  INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  token       TEXT    NOT NULL UNIQUE,
  created_by  INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_share_project ON project_share(project_id);
-- Single active link per project, enforced at the DB level so concurrent
-- creates cannot race. Revoked rows stay for audit.
CREATE UNIQUE INDEX IF NOT EXISTS idx_share_project_active
  ON project_share(project_id)
  WHERE revoked_at IS NULL;

-- Mobile photo-upload sessions for technicians.
--
-- ADDITIVE table for the "Upload from Mobile" feature. Existing tables are
-- untouched. One row = one QR code shown on a desktop test sheet. The opaque
-- token in the QR URL is the only credential the phone needs; it is scoped to
-- exactly one (project, model, test_run) triple so a photo can never land on
-- the wrong test. Sessions expire (default 60 min) and are revoked when the
-- technician closes the QR dialog or the report is approved.
CREATE TABLE IF NOT EXISTS mobile_upload_session (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token         TEXT    NOT NULL UNIQUE,
  project_id    INTEGER NOT NULL REFERENCES project(id) ON DELETE CASCADE,
  model_id      INTEGER REFERENCES instrument_model(id) ON DELETE CASCADE,
  test_run_id   INTEGER NOT NULL REFERENCES test_run(id) ON DELETE CASCADE,
  created_by    INTEGER REFERENCES "user"(id) ON DELETE SET NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at    TIMESTAMPTZ NOT NULL,
  upload_count  INTEGER NOT NULL DEFAULT 0,
  last_upload_at TIMESTAMPTZ,
  revoked_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_mobile_session_token ON mobile_upload_session(token);
CREATE INDEX IF NOT EXISTS idx_mobile_session_run ON mobile_upload_session(test_run_id);
